import type { Entry, HarCookie, HarEntry } from '../types'

const csvCell = (value: string | number) => {
  const s = String(value)
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
}

export function toCsv(entries: readonly Entry[]): string {
  const header = [
    '#',
    'Method',
    'URL',
    'Domain',
    'Status',
    'Type',
    'Size (bytes)',
    'Transferred (bytes)',
    'Time (ms)',
    'Started',
  ]
  const rows = entries.map((e) => [
    e.id + 1,
    e.method,
    e.url,
    e.host,
    e.status,
    e.type,
    Math.max(0, e.size),
    Math.max(0, e.transferSize),
    Math.round(e.time),
    e.raw.startedDateTime ?? '',
  ])
  return [header, ...rows].map((row) => row.map(csvCell).join(',')).join('\n')
}

interface ResolvedCookie extends HarCookie {
  domain: string
}

/** All request + response cookies, de-duplicated by domain and name (first wins). */
export function collectCookies(entries: readonly HarEntry[]): ResolvedCookie[] {
  const seen = new Set<string>()
  const out: ResolvedCookie[] = []
  for (const entry of entries) {
    let host = ''
    try {
      host = new URL(entry.request?.url ?? '').hostname
    } catch {
      /* relative or malformed URL */
    }
    for (const c of [...(entry.request?.cookies ?? []), ...(entry.response?.cookies ?? [])]) {
      const domain = c.domain || host
      const key = `${domain}|${c.name}`
      if (seen.has(key)) continue
      seen.add(key)
      out.push({ ...c, domain })
    }
  }
  return out
}

/** Netscape cookies.txt — understood by curl, wget and most browser extensions. */
export function toNetscapeCookies(entries: readonly HarEntry[]): string {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# https://curl.se/docs/http-cookies.html',
    '# Generated by HAR Viewer',
    '',
  ]
  for (const c of collectCookies(entries)) {
    const expires = c.expires ? Math.floor(Date.parse(c.expires) / 1000) || 0 : 0
    const includeSubdomains = c.domain.startsWith('.') ? 'TRUE' : 'FALSE'
    lines.push(
      [
        c.domain,
        includeSubdomains,
        c.path || '/',
        c.secure ? 'TRUE' : 'FALSE',
        expires,
        c.name,
        c.value,
      ].join('\t'),
    )
  }
  return `${lines.join('\n')}\n`
}

export function toCookieJson(entries: readonly HarEntry[]): string {
  const cookies = collectCookies(entries).map((c) => ({
    name: c.name,
    value: c.value,
    domain: c.domain,
    path: c.path || '/',
    secure: c.secure ?? false,
    httpOnly: c.httpOnly ?? false,
    ...(c.sameSite ? { sameSite: c.sameSite } : {}),
    ...(c.expires ? { expires: c.expires } : {}),
  }))
  return JSON.stringify(cookies, null, 2)
}

/** A `Cookie:` header value from the request cookies. */
export function toCookieHeader(entries: readonly HarEntry[]): string {
  const seen = new Set<string>()
  const pairs: string[] = []
  for (const entry of entries) {
    for (const c of entry.request?.cookies ?? []) {
      if (seen.has(c.name)) continue
      seen.add(c.name)
      pairs.push(`${c.name}=${c.value}`)
    }
  }
  return pairs.join('; ')
}
