import type { HarEntry, HarLog, HarCookie, ParsedEntry } from './types'

export function exportHarEntries(
  rawEntries: HarEntry[],
  label: string,
  harData: HarLog | null
): void {
  const exportData = {
    log: {
      version: harData?.version || '1.2',
      creator: harData?.creator || { name: 'HAR Viewer Export', version: '1.0' },
      pages: harData?.pages || [],
      entries: rawEntries,
    },
  }
  const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `har-export-${rawEntries.length}-${label}.har`
  a.click()
  URL.revokeObjectURL(url)
}

export function buildCurl(raw: HarEntry): string {
  let cmd = `curl '${raw.request?.url || ''}'`
    ; (raw.request?.headers || []).forEach((h) => {
      if (h.name.toLowerCase() !== 'cookie') cmd += ` \\\n  -H '${h.name}: ${h.value}'`
    })
  const cookies = (raw.request?.cookies || []).map((c) => `${c.name}=${c.value}`).join('; ')
  if (cookies) cmd += ` \\\n  -H 'Cookie: ${cookies}'`
  if (raw.request?.method && raw.request.method !== 'GET')
    cmd += ` \\\n  -X ${raw.request.method}`
  if (raw.request?.postData?.text)
    cmd += ` \\\n  --data-raw '${raw.request.postData.text.replace(/'/g, "'\\''")}'`
  return cmd
}

/** Export cookies in Netscape cookies.txt format (curl, wget, browsers) */
export function exportCookiesNetscape(entries: HarEntry[], label: string): void {
  const lines = ['# Netscape HTTP Cookie File', '# https://curl.se/docs/http-cookies.html', '# Generated by HAR Viewer', '']
  const seen = new Set<string>()

  for (const entry of entries) {
    const allCookies: (HarCookie & { _domain?: string })[] = [
      ...(entry.request?.cookies || []),
      ...(entry.response?.cookies || []),
    ]
    let urlDomain = ''
    try { urlDomain = new URL(entry.request?.url || '').hostname } catch { /* */ }

    for (const c of allCookies) {
      const domain = c.domain || urlDomain
      const key = `${domain}|${c.name}`
      if (seen.has(key)) continue
      seen.add(key)

      const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE'
      const path = c.path || '/'
      const secure = c.secure ? 'TRUE' : 'FALSE'
      const expires = c.expires ? Math.floor(new Date(c.expires).getTime() / 1000) : 0
      lines.push(`${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expires}\t${c.name}\t${c.value}`)
    }
  }

  const blob = new Blob([lines.join('\n') + '\n'], { type: 'text/plain' })
  downloadBlob(blob, `cookies-${label}.txt`)
}

/** Export cookies as JSON */
export function exportCookiesJson(entries: HarEntry[], label: string): void {
  const cookies: Record<string, unknown>[] = []
  const seen = new Set<string>()

  for (const entry of entries) {
    let urlDomain = ''
    try { urlDomain = new URL(entry.request?.url || '').hostname } catch { /* */ }

    for (const c of [...(entry.request?.cookies || []), ...(entry.response?.cookies || [])]) {
      const domain = c.domain || urlDomain
      const key = `${domain}|${c.name}`
      if (seen.has(key)) continue
      seen.add(key)
      cookies.push({
        name: c.name,
        value: c.value,
        domain,
        path: c.path || '/',
        secure: c.secure || false,
        httpOnly: c.httpOnly || false,
        ...(c.sameSite ? { sameSite: c.sameSite } : {}),
        ...(c.expires ? { expires: c.expires } : {}),
      })
    }
  }

  const blob = new Blob([JSON.stringify(cookies, null, 2)], { type: 'application/json' })
  downloadBlob(blob, `cookies-${label}.json`)
}

/** Copy cookies as header string */
export function buildCookieHeader(entries: HarEntry[]): string {
  const pairs: string[] = []
  const seen = new Set<string>()
  for (const entry of entries) {
    for (const c of (entry.request?.cookies || [])) {
      if (!seen.has(c.name)) {
        seen.add(c.name)
        pairs.push(`${c.name}=${c.value}`)
      }
    }
  }
  return pairs.join('; ')
}

/** Build fetch() snippet */
export function buildFetch(raw: HarEntry): string {
  const url = raw.request?.url || ''
  const method = raw.request?.method || 'GET'
  const headers: Record<string, string> = {}
    ; (raw.request?.headers || []).forEach((h) => {
      const n = h.name.toLowerCase()
      if (n === 'host' || n === 'content-length' || n === 'connection') return
      headers[h.name] = h.value
    })
  const cookies = (raw.request?.cookies || []).map((c) => `${c.name}=${c.value}`).join('; ')
  if (cookies) headers['Cookie'] = cookies

  let code = `fetch('${url}'`
  const opts: string[] = []
  if (method !== 'GET') opts.push(`  method: '${method}'`)
  if (Object.keys(headers).length) {
    opts.push(`  headers: ${JSON.stringify(headers, null, 4).replace(/\n/g, '\n  ')}`)
  }
  if (raw.request?.postData?.text) {
    opts.push(`  body: ${JSON.stringify(raw.request.postData.text)}`)
  }
  if (opts.length) {
    code += `, {\n${opts.join(',\n')}\n}`
  }
  code += ')'
  return code
}

/** Build axios snippet */
export function buildAxios(raw: HarEntry): string {
  const url = raw.request?.url || ''
  const method = (raw.request?.method || 'GET').toLowerCase()
  const headers: Record<string, string> = {}
    ; (raw.request?.headers || []).forEach((h) => {
      const n = h.name.toLowerCase()
      if (n === 'host' || n === 'content-length' || n === 'connection') return
      headers[h.name] = h.value
    })
  const cookies = (raw.request?.cookies || []).map((c) => `${c.name}=${c.value}`).join('; ')
  if (cookies) headers['Cookie'] = cookies

  const config: string[] = [`  url: '${url}'`, `  method: '${method}'`]
  if (Object.keys(headers).length) {
    config.push(`  headers: ${JSON.stringify(headers, null, 4).replace(/\n/g, '\n  ')}`)
  }
  if (raw.request?.postData?.text) {
    try {
      JSON.parse(raw.request.postData.text)
      config.push(`  data: ${raw.request.postData.text}`)
    } catch {
      config.push(`  data: ${JSON.stringify(raw.request.postData.text)}`)
    }
  }
  return `axios({\n${config.join(',\n')}\n})`
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

/** Export entries as CSV */
export function exportCsv(entries: ParsedEntry[], label: string): void {
  const header = 'URL,Method,Status,Size (bytes),Time (ms),Content Type,Domain'
  const rows = entries.map((e) => {
    const esc = (s: string) => `"${s.replace(/"/g, '""')}"`
    return `${esc(e.url)},${e.method},${e.status},${Math.max(0, e.size)},${Math.round(e.time)},${esc(e.contentType)},${esc(e.host)}`
  })
  const csv = [header, ...rows].join('\n')
  const blob = new Blob([csv], { type: 'text/csv' })
  downloadBlob(blob, `har-export-${entries.length}-${label}.csv`)
}

/** Sensitive header names to redact */
const SENSITIVE_HEADERS = new Set([
  'authorization', 'cookie', 'set-cookie', 'x-api-key', 'x-auth-token',
  'proxy-authorization', 'x-csrf-token', 'x-xsrf-token', 'x-forwarded-for',
  'x-real-ip', 'x-amz-security-token', 'x-amz-credential',
])

/** Export sanitized HAR with sensitive data redacted */
export function exportSanitizedHar(
  rawEntries: HarEntry[],
  label: string,
  harData: HarLog | null
): void {
  const sanitized = rawEntries.map((e) => {
    const entry = JSON.parse(JSON.stringify(e)) as HarEntry
    // Redact request headers
    if (entry.request?.headers) {
      entry.request.headers = entry.request.headers.map((h) =>
        SENSITIVE_HEADERS.has(h.name.toLowerCase()) ? { ...h, value: '[REDACTED]' } : h
      )
    }
    // Redact response headers
    if (entry.response?.headers) {
      entry.response.headers = entry.response.headers.map((h) =>
        SENSITIVE_HEADERS.has(h.name.toLowerCase()) ? { ...h, value: '[REDACTED]' } : h
      )
    }
    // Redact cookies
    if (entry.request?.cookies) {
      entry.request.cookies = entry.request.cookies.map((c) => ({ ...c, value: '[REDACTED]' }))
    }
    if (entry.response?.cookies) {
      entry.response.cookies = entry.response.cookies.map((c) => ({ ...c, value: '[REDACTED]' }))
    }
    // Redact postData if it looks like it contains auth
    if (entry.request?.postData?.text) {
      const t = entry.request.postData.text.toLowerCase()
      if (t.includes('password') || t.includes('token') || t.includes('secret') || t.includes('api_key')) {
        entry.request.postData.text = '[REDACTED - may contain sensitive data]'
      }
    }
    return entry
  })

  const exportData = {
    log: {
      version: harData?.version || '1.2',
      creator: { name: 'HAR Viewer (Sanitized)', version: '1.0' },
      pages: harData?.pages || [],
      entries: sanitized,
    },
  }
  const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' })
  downloadBlob(blob, `har-sanitized-${sanitized.length}-${label}.har`)
}

/** Merge multiple HAR logs into one */
export function mergeHarLogs(logs: { log: HarLog; fileName: string }[]): HarLog {
  const allEntries: HarEntry[] = []
  const allPages: HarLog['pages'] = []
  for (const { log } of logs) {
    const entries = log.entries || []
    allEntries.push(...entries)
    if (log.pages) allPages.push(...log.pages)
  }
  // Sort by startedDateTime
  allEntries.sort((a, b) => new Date(a.startedDateTime).getTime() - new Date(b.startedDateTime).getTime())
  return {
    version: '1.2',
    creator: { name: 'HAR Viewer (Merged)', version: '1.0' },
    pages: allPages,
    entries: allEntries,
  }
}
